PROJECT_TYPE="web"
WEB_SERVER="apache"
INSTALL_PHP="true"
PHP_VERSION="8.3"
PHP_FRAMEWORK="laravel"
INSTALL_NODE="true"
NODE_MANAGER="pnpm"
DB_TYPE="postgresql"
INSTALL_REDIS="false"
INSTALL_XDEBUG="false"
INSTALL_SSL_LOCAL="false"
GIT_INIT="true"
GITHUB_REPO="ask"
