# Valeurs par défaut — surchargeables via profil ou arguments CLI

TIMEZONE="Europe/Paris"
LOCALE="fr_FR.UTF-8"
LOCALE_EXTRA="en_US.UTF-8"

# Web
WEB_DEFAULT_PATH="/var/www"
WEB_SERVER="apache"
PHP_VERSION="8.3"
PHP_FRAMEWORK="vanilla"
NODE_MANAGER="pnpm"
NODE_VERSION="lts"

# Python
PYTHON_DEFAULT_PATH="$HOME"
PYTHON_VERSION="system"
PYTHON_DEPS_MANAGER="pip"
PYTHON_PROJECT_TYPE="script"

# Base de données
DB_TYPE="none"

# Services
INSTALL_REDIS="false"
INSTALL_XDEBUG="false"
INSTALL_SSL_LOCAL="false"

# Git
GIT_INIT="true"
GITHUB_REPO="none"

# WSL
WSL_MEMORY="8GB"
WSL_PROCESSORS="4"
WSL_SWAP="4GB"
